"""esquema inicial de la BD de la app

Revision ID: 54489ef6eafd
Revises: 
Create Date: 2026-09-03 14:27:58.733800
"""
from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401
import sqlmodel  # noqa: F401
from alembic import op  # noqa: F401



revision: str = '54489ef6eafd'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fuente', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_table', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('before_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('after_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_audit_log_action'), 'app_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_app_audit_log_module'), 'app_audit_log', ['module'], unique=False)
    op.create_index(op.f('ix_app_audit_log_ts'), 'app_audit_log', ['ts'], unique=False)
    op.create_table('app_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_config_key'), 'app_config', ['key'], unique=False)
    op.create_index(op.f('ix_app_config_user_id'), 'app_config', ['user_id'], unique=False)
    op.create_table('app_email_send_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_email_send_log_employee_code'), 'app_email_send_log', ['employee_code'], unique=False)
    op.create_index(op.f('ix_app_email_send_log_job_id'), 'app_email_send_log', ['job_id'], unique=False)
    op.create_table('app_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('params_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('result_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_job_created_at'), 'app_job', ['created_at'], unique=False)
    op.create_index(op.f('ix_app_job_tipo'), 'app_job', ['tipo'], unique=False)
    op.create_table('app_loan_history_migrated',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ingreso', sa.Float(), nullable=False),
    sa.Column('egreso', sa.Float(), nullable=False),
    sa.Column('concepto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('numero_fila', sa.Integer(), nullable=True),
    sa.Column('observaciones', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origen', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_loan_history_migrated_empleado'), 'app_loan_history_migrated', ['empleado'], unique=False)
    op.create_table('app_role_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_role_permission_module'), 'app_role_permission', ['module'], unique=False)
    op.create_index(op.f('ix_app_role_permission_role'), 'app_role_permission', ['role'], unique=False)
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_username'), 'app_user', ['username'], unique=True)
    op.create_table('app_user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_role_role'), 'app_user_role', ['role'], unique=False)
    op.create_index(op.f('ix_app_user_role_user_id'), 'app_user_role', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_user_role_user_id'), table_name='app_user_role')
    op.drop_index(op.f('ix_app_user_role_role'), table_name='app_user_role')
    op.drop_table('app_user_role')
    op.drop_index(op.f('ix_app_user_username'), table_name='app_user')
    op.drop_table('app_user')
    op.drop_index(op.f('ix_app_role_permission_role'), table_name='app_role_permission')
    op.drop_index(op.f('ix_app_role_permission_module'), table_name='app_role_permission')
    op.drop_table('app_role_permission')
    op.drop_index(op.f('ix_app_loan_history_migrated_empleado'), table_name='app_loan_history_migrated')
    op.drop_table('app_loan_history_migrated')
    op.drop_index(op.f('ix_app_job_tipo'), table_name='app_job')
    op.drop_index(op.f('ix_app_job_created_at'), table_name='app_job')
    op.drop_table('app_job')
    op.drop_index(op.f('ix_app_email_send_log_job_id'), table_name='app_email_send_log')
    op.drop_index(op.f('ix_app_email_send_log_employee_code'), table_name='app_email_send_log')
    op.drop_table('app_email_send_log')
    op.drop_index(op.f('ix_app_config_user_id'), table_name='app_config')
    op.drop_index(op.f('ix_app_config_key'), table_name='app_config')
    op.drop_table('app_config')
    op.drop_index(op.f('ix_app_audit_log_ts'), table_name='app_audit_log')
    op.drop_index(op.f('ix_app_audit_log_module'), table_name='app_audit_log')
    op.drop_index(op.f('ix_app_audit_log_action'), table_name='app_audit_log')
    op.drop_table('app_audit_log')
    # ### end Alembic commands ###
