"""Dominio de Gestión de Faltas / Permisos / Suspensiones / Restas de Horas.

Cálculos puros (sin I/O). El acceso a datos vive en `core/repos/faltas.py`.
Trasplante de `sistema_sanciones_RRHH/nucleo_modular/faltas_calculo.py`.
"""

from core.faltas.calculo import (
    FACTOR_CONV_50A100,
    HORAS_POR_FALTA,
    MAX_FALTAS,
    TIPOS_REGISTRO_MASIVO,
    TIPOS_REGISTRO_UNO_A_UNO,
    TIPOS_VALIDACION_MASIVA,
    calcular_descuento_horas_extra,
    calcular_horas,
    calcular_horas_levantamiento_suspension,
    calcular_porcentaje_descuento_suspension,
    calcular_resta_horas,
    calcular_resultados_resta,
    calcular_suspension,
    concatenar_observ,
    contar_faltas_por_cedula,
    evaluar_alerta_faltas,
    formatear_cedula,
    generar_observacion,
    generar_observacion_levantamiento,
    generar_observacion_suspension,
    mapear_pegado_a_campos,
    obtener_fecha_fin_mes,
    parse_fecha,
    parse_line,
    parse_linea_pegado,
    validar_fila_grid_masivo,
    validar_fila_registro,
    validar_longitud_observacion,
)

__all__ = [
    "FACTOR_CONV_50A100",
    "HORAS_POR_FALTA",
    "MAX_FALTAS",
    "TIPOS_REGISTRO_MASIVO",
    "TIPOS_REGISTRO_UNO_A_UNO",
    "TIPOS_VALIDACION_MASIVA",
    "calcular_descuento_horas_extra",
    "calcular_horas",
    "calcular_horas_levantamiento_suspension",
    "calcular_porcentaje_descuento_suspension",
    "calcular_resta_horas",
    "calcular_resultados_resta",
    "calcular_suspension",
    "concatenar_observ",
    "contar_faltas_por_cedula",
    "evaluar_alerta_faltas",
    "formatear_cedula",
    "generar_observacion",
    "generar_observacion_levantamiento",
    "generar_observacion_suspension",
    "mapear_pegado_a_campos",
    "obtener_fecha_fin_mes",
    "parse_fecha",
    "parse_line",
    "parse_linea_pegado",
    "validar_fila_grid_masivo",
    "validar_fila_registro",
    "validar_longitud_observacion",
]
